### ISSUE TITLE
Port `DynamicGraph` over to `raphtory` crate

### ISSUE THREAD

**Issue by ricopinazo** [Pometry/Raphtory#1002]
DynamicGraph is being used as well in `raphtory-graphql` crate. For now it was just temporary copied over, but it should be in `raphtory` crate instead. Several things need to be done on this:
- Create `development` feature flag that includes `DynamicGraph` to be used by our own crates
- There are many struct members which are public only because we needed them to be for `DynamicGraph` implementation to work. Now that it is in the same crate, we can turn them back to private.
- Double check if when developing custom algorithms we need to have now `raphtory` as a dependency and consider re-exporting `DynamicGraph` from the python crate if that is the only struct we need from `raphtory`

**Comment by ljeub-pometry** [comment]
This is irrelevant now that DynamicGraph no longer exists and python wrappers are part of the core crate (see #1055)
