### ISSUE TITLE
Swap all algorithms, possible also swap internals to use `hashbrown` hashmap which is way faster than default hashmap and fxhashmap

### ISSUE THREAD

**Issue by Haaroon** [Pometry/Raphtory#1110]
https://github.com/rust-lang/hashbrown 

speeed

ensure you dont change concurrent ones if any

**Comment by Haaroon** [comment]
demo code used 

```
use hashbrown::HashMap;
use fxhash::FxHashMap;
use std::time::{Instant, Duration};

fn main() {
    // Generate some sample data
    println!("Generating data...");
    let keys: Vec<String> = (0..10_000_000).map(|i| format!("key_{}", i)).collect();
    let values: Vec<u32> = (0..10_000_000).collect();

    // Test FxHashMap for insertion and retrieval
    println!("Testing FxHashMap insertion...");
    let fx_start_time = Instant::now();
    let mut fx_map: FxHashMap<String, u32> = FxHashMap::default();
    for i in 0..keys.len() {
        fx_map.insert(keys[i].clone(), values[i]);
    }
    let fx_insert_duration = fx_start_time.elapsed();

    println!("Testing FxHashMap retrieval...");
    let fx_retrieve_start_time = Instant::now();
    for i in 0..keys.len() {
        let _ = fx_map.get(&keys[i]);
    }
    let fx_retrieve_duration = fx_retrieve_start_time.elapsed();

    // Test HashMap for insertion and retrieval
    println!("Testing HashMap insertion...");
    let std_start_time = Instant::now();
    let mut std_map: HashMap<String, u32> = HashMap::new();
    for i in 0..keys.len() {
        std_map.insert(keys[i].clone(), values[i]);
    }
    let std_insert_duration = std_start_time.elapsed();

    println!("Testing HashMap retrieval...");
    let std_retrieve_start_time = Instant::now();
    for i in 0..keys.len() {
        let _ = std_map.get(&keys[i]);
    }
    let std_retrieve_duration = std_retrieve_start_time.elapsed();

    println!("FxHashMap Insertion Time: {:?}", fx_insert_duration);
    println!("FxHashMap Retrieval Time: {:?}", fx_retrieve_duration);
    println!("HashMap Insertion Time:  {:?}", std_insert_duration);
    println!("HashMap Retrieval Time:  {:?}", std_retrieve_duration);
}
``` 

10m insertion and deletions using default hashmap and fxhashmap

10m
run1
FxHashMap Insertion Time: 8.728446733s
FxHashMap Retrieval Time: 2.275474473s
HashMap Insertion Time:  4.849721337s
HashMap Retrieval Time:  3.187094012s
run2
FxHashMap Insertion Time: 4.809728093s
FxHashMap Retrieval Time: 1.833095641s
HashMap Insertion Time:  5.371272675s
HashMap Retrieval Time:  2.614374231s
run3
FxHashMap Insertion Time: 4.991335531s
FxHashMap Retrieval Time: 2.064199099s
HashMap Insertion Time:  4.781259631s
HashMap Retrieval Time:  2.65044565s
run4
FxHashMap Insertion Time: 5.035220164s
FxHashMap Retrieval Time: 2.19570548s
HashMap Insertion Time:  6.126805529s
HashMap Retrieval Time:  3.12072097s



10m insertions and deletions using hashbrown hashmap vs fxhashmap
run1
FxHashMap Insertion Time: 5.326364064s
FxHashMap Retrieval Time: 2.179339305s
HashMap Insertion Time:  3.826072406s
HashMap Retrieval Time:  1.579312214s
run2
FxHashMap Insertion Time: 5.151572132s
FxHashMap Retrieval Time: 2.191153685s
HashMap Insertion Time:  3.605123069s
HashMap Retrieval Time:  1.547814434s
run3
FxHashMap Insertion Time: 5.042917727s
FxHashMap Retrieval Time: 2.041452919s
HashMap Insertion Time:  3.561159494s
HashMap Retrieval Time:  1.607227734s

**Comment by miratepuffin** [comment]
Test with criterion before deciding which to use.
