### ISSUE TITLE
pandas key error gets squished in load_edges_from_df

### ISSUE THREAD

**Issue by narnolddd** [Pometry/Raphtory#1224]
Loving the load_edges_from_pandas functionality, super useful! 

Just noticed that something which probably should come out as a Pandas KeyError or similar (specifying a source, destination or time column name which doesn't exist) comes out as a slightly misleading error "source and target columns must be either u64 or text, time column must be i64" which I think is in there as a catch-all.

**Comment by miratepuffin** [comment]
Going to fix as part of #1245
