### ISSUE TITLE
Add English Simplified version for some rust and python public facing methods

### ISSUE THREAD

**Issue by Haaroon** [Pometry/Raphtory#1388]
Things like `graph.neighbours` add a wrapper so you can do the Simplified version `graph.neighbors`

**Comment by miratepuffin** [comment]
NEVER 🇬🇧 🇬🇧 🇬🇧 🇬🇧 🇬🇧 🇬🇧 🇬🇧 🇬🇧 🇬🇧 🇬🇧 🇬🇧
