### ISSUE TITLE
Properties API out of sync rust to python 

### ISSUE THREAD

**Issue by Haaroon** [Pometry/Raphtory#1462]
Python:  `v.properties.constant.as_dict()`
Rust: `g.node(b).unwrap().properties().constant().as_map()`

~~Python: `v.properties.temporal.histories()`~~
~~Rust: No `.histories()` function on temporal props~~

**Comment by Haaroon** [comment]
added .histories in https://github.com/Pometry/Raphtory/pull/1463/files

**Comment by miratepuffin** [comment]
I think the top example is just language appropriate
