### ISSUE TITLE
As the ISO-GQL is published, any plan to support it?

### ISSUE THREAD

**Issue by haoxins** [Pometry/Raphtory#1577]
See https://www.iso.org/standard/76120.html

**Comment by miratepuffin** [comment]
Hay @haoxins - we are currently building support for cypher, as its the predominant language we get asked for.

If we see a large amount of uptake for GQL we shall most definetly look to support :)

**Comment by Alnaimi-** [comment]
Worth mentioning that we may also be able to release ANSI-SQL support in same release for Cypher. 

Is that still on agenda @miratepuffin ?

**Comment by miratepuffin** [comment]
Indeed! Raphtory 0.9.0 alreayd looking 🔥
