### ISSUE TITLE
temporally_reachable_nodes

### ISSUE THREAD

**Issue by izzy-was** [Pometry/Raphtory#1864]
I am trying to implement temporally_reachable_nodes() and it is returning all nodes in the graph, no matter the graph and no matter the starting node, even starting nodes in small disconnected components. I am restricted to v0.6.1 unfortunately, so maybe this is the problem. Any help would be much appreciated!

**Comment by miratepuffin** [comment]
Hi @izzy-was, yeah this could well be a problem with that version. I vaguely remember we fixed an error around this last year. Why can't you use 13.1?

**Comment by izzy-was** [comment]
Hi Ben,

Thanks for your reply. I'm looking at various network analysis packages for
a work project, but apparently the analytics platform we use can't support
the latest version for various reasons. Fingers crossed it may get updated,
but I'm stuck at the moment.

Many thanks,

Izzy

**Comment by miratepuffin** [comment]
Would you be able to provide me with a small example so I can run it on the latest version and see if it is still an issue?

If you also have some time to go through your general problem area with me I can advise on the best way to use Raphtory. If you would like to join the slack we can DM there (https://join.slack.com/t/raphtory/shared_invite/zt-1998kdihw-nna1f23GH25JJ46Apn0gjA)

**Comment by miratepuffin** [comment]
Hi @izzy-was, any update on this, or can I close the ticket?
