### ISSUE TITLE
Documentation clarification on vertex.ID

### ISSUE THREAD

**Issue by nrs1729** [Pometry/Raphtory#566]
The documentation explaining vertex IDs here https://docs.raphtory.com/en/master/_static/com/raphtory/api/analysis/visitor/Vertex.html#IDType is slightly confusing - it says it returns an ID type when it actually returns the ID in an IDType object (I think?), and the description of IDType above it could be clarified to explain it's an alias for whichever type the ID is (Long, String etc).

**Comment by miratepuffin** [comment]
Hi @nrs1729 This has been totally updated in the new rust-based version of Raphtory. Closing for now, but let me know if you have any other issues.
