### ISSUE TITLE
Feature suggestion: Graph Views/"Reversible" Filters

### ISSUE THREAD

**Issue by narnolddd** [Pometry/Raphtory#785]
May be not for this (scala) version of Raphtory but in the future it would be great to have some way of working with a graph view, where one can apply filters and then roll them back again. An analogy is the [graph-tool view class](https://graph-tool.skewed.de/static/doc/quickstart.html#graph-views) where the view object shares the data with the original graph.

## Motivating example: triangle counting/enumeration

A very optimised algorithm for triangle counting in power law graphs involves pruning the graph based on 2-cores, which is to recursively remove nodes with degree <2 (since they cannot be involved in triangles). The second step in this algorithm is to direct each edge so that it points from low degree to high degree (the AdjPlus algorithm). Finally, we check if each pair of outgoing edges from a vertex are themselves connected by an edge. The second step minimises the number of messages going around (I think?) or the number of set intersections being done to find common neighbours. In any case it makes a huge difference (with just the first optimisation in my algo, it went down to 2hrs in my dataset from 8hrs before).

The trouble is that without some filtering done, the algorithm gets ugly to write and the amount of extra state being stored is huge. e.g. keeping track of which neighbours are still in the graph after the 2-core filter, which neighbours are of higher degree than me after this k core filter, whereas if you were fully filtering the graph it would be totally straightforward. I think this kind of filtering is useful for other motif-related stuff as well.

**Comment by miratepuffin** [comment]
Fixed with subgraphs
