### ISSUE TITLE
Change all Python REPLs to match function names

### ISSUE THREAD

**Issue by Haaroon** [Pometry/Raphtory#893]
e = g.vertex(_id).out_edges().first()

> Edge(source=1108727, target=208424, earliest_time=1, latest_time=1)

Yet I cannot do e.source or e.target, i must do e.src() or e.dst()

Change the repl fo the names it prints matches the available functions

**Comment by rachchan** [comment]
https://hackmd.io/@KjYn38DjSsOBuPZ46-ubTw/BJ2xIIkkp
