### ISSUE TITLE
New documentation page on time APIs

### ISSUE THREAD

**Issue by miratepuffin** [Pometry/Raphtory#923]
Whilst we cover this in the examples - we need a documentation page on the time APIs i.e. `at` `window` `rolling` and `expanding` being called on the vertices/edge/graph.

**Comment by aryanraj2713** [comment]
I want to work on this issue , please assign

**Comment by miratepuffin** [comment]
Hi @aryanraj2713 please feel free! Our docs can be built via `make html` I believe there are instructions in the `CONTRIBUTING.md`.

The docs can consist of both md files and ipython notebooks - my thoughts were to make something similar to the [Lord of the Rings intro](https://github.com/Pometry/Raphtory/blob/master/docs/source/Introduction/ingestion.ipynb), but using the [Enron example](https://github.com/Pometry/Raphtory/blob/master/examples/py/enron/enron.ipynb). 

The Enron emails data could be stripped down to not include the text which should reduce it from ~1Gb to like a couple MB and make it appropriate to update to our example data repo (https://github.com/Raphtory/Data).

Let me know if you need a hand with anything!
