### ISSUE TITLE
Add edge deletions to the model

### ISSUE THREAD

**Issue by miratepuffin** [Pometry/Raphtory#928]
Since the swap to rust we have only supported Additions and property updates to the graph. This was for simplicity and to help with the build out of the initial core. Now that this is all working we need to reenable deletions (starting with edge deletions).

As part of this we need to consider the various semantics we may have - for example if a user asks for a windowed graph and and edge existed for a period of this window, should it be returned?

A second component is the API - we can enable several nice shorthands such as setting the duration on an edge during graph creation.

**Comment by ljeub-pometry** [comment]
Deletions are now supported again #1065 with (hopefully) sensible default semantics (an edge is included in a window if it existed at any time during the window). For edge durations, it probably makes more sense to create a view that uses an edge property for duration (so we don't have any problems if multiple edges between the same vertices overlap).

Created a new issue for durations support: #1067
