### ISSUE TITLE
Out-of-core processing - Codename: Diskbrown

### ISSUE THREAD

**Issue by miratepuffin** [Pometry/Raphtory#941]
Current implementation of Raphtory maintains the graph fully in-memory. The aim of this issue is to investigate options to spill portions of the graph to disk, which can be read back in as required.

This should be useful to analyse graphs much larger than the available memory on a machine - especially when running rolling windows etc. when very clear segments of data are required.

This issue is a stub and will be updated further as it is worked on.

**Comment by fabianmurariu** [comment]
- [ ] Figure out what kind of strategy we need to move forward
