### ISSUE TITLE
Properties which change type need to throw an error

### ISSUE THREAD

**Issue by miratepuffin** [Pometry/Raphtory#951]
Currently in python if you add properties to an edge/vertex multiple times with the same key but different value types, only values of the first type are stored, for example:

```python
g.add_vertex(1,1,{"prop1": 1})
g.add_vertex(2,1,{"prop1": "string 1"})
g.add_vertex(3,1,{"prop1": 3})

g.vertex(1).property_history("prop1")
```
```
[(1,1),(3,3)]
```

The resulting vertex will only have the integer values not the string in-between.

This is erroring in the core, but the exception is being swallowed - we either need to make it possible to have properties be multiple value types or at least throw the error in python so that the user knows this data is missing.

**Comment by Haaroon** [comment]
this is very important
