### ISSUE TITLE
Create property object which can host all property APIs

### ISSUE THREAD

**Issue by miratepuffin** [Pometry/Raphtory#956]
There are many property functions available, with several others planned - these are fully duplicated on the vertex/vertices/edge/edges and will soon be added to the graph. As such we should change this up such that all of these objects have a property object which maintains all of the functions. This will remove the duplication and mean we can ensure all types have consistent behaviour. For example:

```python
g = Graph()
g.properties["prop1"].history.times()
g.properties["prop1"].history.values()
g.properties["prop1"].history.pairs/tuples()
g.properties["prop1"].latest()
g.properties["prop1"].sum()
g.properties["prop1"].len()
g.properties["prop1"].avg()
g.properties["prop1"].min()
g.properties["prop1"].max()
g.properties["prop1"].at(123)

g.properties.keys()
```

**Comment by miratepuffin** [comment]
@iamsmkr has added the graph level APIs (#1041) - these will also need to be refactored as part of this issue

**Comment by Haaroon** [comment]
is there a pr?
