### ISSUE TITLE
Some functionality for connected components within core

### ISSUE THREAD

**Issue by narnolddd** [Pometry/Raphtory#962]
Currently weakest connected components returns a dictionary mapping a node to its component id. It would be really useful to go a step further with some different helpers, e.g. a function which returns a list of lists of nodes in each component, a function for some component statistics like largest connected component (lcc) size, relative lcc size, number of connected components.

As a side point, is there a way of having a stopping condition so that a user doesn't need to supply a max number of iterations?

**Comment by miratepuffin** [comment]
Solved now with the algorithm result API
